In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import make_classification
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.impute import SimpleImputer

In [2]:
df = pd.read_csv("allocated_values3.csv")

In [3]:
df.head()

Unnamed: 0  PCOS (Y/N)  Age (yrs)  Weight (Kg)  Height(Cm)        BMI  \
0           0           1         30         85.0       165.0  31.221304   
1           1           1         30         76.0       160.0  29.687500   
2           2           1         28         56.0       152.0  24.238227   
3           3           1         34         57.0       150.0  25.333333   
4           4           1         27         51.0       154.0  21.504470   

   Cycle(R/I)  Pregnant(Y/N)  No. of aborptions  FSH(mIU/mL)  LH(mIU/mL)  \
0           4              0                  0         1.89        0.81   
1           4              0                  0         6.18        2.78   
2           4              0                  0         2.41        1.19   
3           2              0                  0         5.01        6.48   
4           4              0                  0         2.26        2.40   

     FSH/LH  PRL(ng/mL)  Weight gain(Y/N)  Fast food (Y/N)  Reg.Exercise(Y/N)  \
0  2.333333       19.13                 0                1                  0   
1  2.223022       17.98                 1                1                  1   
2  2.025210       45.47                 1                1                  0   
3  0.773148       12.71                 1                1                  0   
4  0.941667       15.22                 1                1                  1   

   Allocated Values  
0                 6  
1                 6  
2                 4  
3                 4  
4                 4

In [4]:
X=df.drop(["Unnamed: 0","Allocated Values"],axis = 1)

In [5]:
y=df["Allocated Values"]

In [6]:
print(X.columns)

Index(['PCOS (Y/N)', 'Age (yrs)', 'Weight (Kg)', 'Height(Cm)', 'BMI',
       'Cycle(R/I)', 'Pregnant(Y/N)', 'No. of aborptions', 'FSH(mIU/mL)',
       'LH(mIU/mL)', 'FSH/LH', 'PRL(ng/mL)', 'Weight gain(Y/N)',
       'Fast food (Y/N)', 'Reg.Exercise(Y/N)'],
      dtype='object')


In [7]:
print(y)

0      6
1      6
2      4
3      4
4      4
      ..
108    6
109    4
110    6
111    4
112    6
Name: Allocated Values, Length: 113, dtype: int64


In [8]:
X.shape,y.shape

((113, 15), (113,))

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=17, test_size=0.2)

In [10]:
X_train.shape, y_train.shape

((90, 15), (90,))

In [11]:
X_test.shape, y_test.shape

((23, 15), (23,))

In [12]:
scaler = StandardScaler()

In [13]:
X_train = scaler.fit_transform(X_train)

In [14]:
X_test = scaler.transform(X_test)

In [15]:
model = LogisticRegression(random_state=42)

In [16]:
#imputer = SimpleImputer(strategy='mean')

In [34]:
#X_train_imputed = imputer.fit_transform(X_train)

In [17]:
model.fit(X_train, y_train)

LogisticRegression(random_state=42)

In [18]:
y_pred = model.predict(X_test)

In [19]:
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 1.0


In [20]:
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Confusion Matrix:
 [[ 2  0  0]
 [ 0 12  0]
 [ 0  0  9]]


In [21]:
print("Classification Report:\n", classification_report(y_test, y_pred))

Classification Report:
               precision    recall  f1-score   support

           2       1.00      1.00      1.00         2
           4       1.00      1.00      1.00        12
           6       1.00      1.00      1.00         9

    accuracy                           1.00        23
   macro avg       1.00      1.00      1.00        23
weighted avg       1.00      1.00      1.00        23



In [22]:
print(model.score(X_test, y_test))

1.0


In [23]:
print(y_pred)

[4 6 4 4 4 4 4 4 6 6 6 6 6 4 6 6 2 4 2 4 4 6 4]


In [51]:
print(y_test)

55     6
79     4
43     4
106    4
34     4
28     4
87     4
9      4
82     4
46     4
16     4
48     4
23     4
52     4
78     4
107    4
103    6
42     4
64     6
72     4
4      4
59     4
102    4
Name: Allocated Values, dtype: int64
